// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqbhfgcocvcellvvqyoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYmhmZ2NvY3ZjZWxsdnZxeW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDQwNjMsImV4cCI6MjA2MzgyMDA2M30.6tqX97ZUdFCJ3yMlFUhQVpdqREWSzXH2NHFwQgTYjSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);